### ISSUE TITLE
VirtualView cannot be null here

### ISSUE THREAD

**Issue by azapatac** [LuckyDucko/Mopups#91] opened 2023-10-26 17:11 UTC
`Microsoft.Maui.Handlers.ViewHandler2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_VirtualView()
Mopups.Platforms.Android.Renderers.PopupPageRenderer.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom)
Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4)`

<img width="545" alt="image" src="https://github.com/LuckyDucko/Mopups/assets/8869059/761bde87-b669-4f90-86ba-be30ad67dd53">

**Comment by prok155** [comment] 2023-12-19 18:50
I also saw the same crash in my google play console, but unfortunately can't reporduce that.

```
Fatal Exception: android.runtime.JavaProxyThrowable: System.InvalidOperationException: VirtualView cannot be null here
   at Microsoft.Maui.Handlers.ViewHandler`2[[Microsoft.Maui.IContentView, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[Microsoft.Maui.Platform.ContentViewGroup, Microsoft.Maui, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].get_VirtualView()
   at Mopups.Platforms.Android.Renderers.PopupPageRenderer.OnLayout(Boolean changed, Int32 left, Int32 top, Int32 right, Int32 bottom)
   at Android.Views.ViewGroup.n_OnLayout_ZIIII(IntPtr jnienv, IntPtr native__this, Boolean changed, Int32 l, Int32 t, Int32 r, Int32 b)
   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPZIIII_V(_JniMarshal_PPZIIII_V callback, IntPtr jnienv, IntPtr klazz, Boolean p0, Int32 p1, Int32 p2, Int32 p3, Int32 p4)
       at crc648efb837642500d81.PopupPageRenderer.n_onLayout(PopupPageRenderer.java)
       at crc648efb837642500d81.PopupPageRenderer.onLayout(PopupPageRenderer.java:62)
       at android.view.View.layout(View.java:16992)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
       at android.view.View.layout(View.java:16992)
       at android.view.ViewGroup.layout(ViewGroup.java:5409)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2483)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2185)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7057)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
       at android.view.Choreographer.doCallbacks(Choreographer.java:606)
       at android.view.Choreographer.doFrame(Choreographer.java:576)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6939)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)```

**Comment by MarcosCostaDev** [comment] 2024-01-28 01:38
I just found the same issue on **version 1.3.0** after the merge of #100 

![image](https://github.com/LuckyDucko/Mopups/assets/4077961/9be58587-cb4f-455d-aa4a-f0dfd1856b73)

The scenario is when I try to close the popup via the service `IPopupNavigation.PopAsync();` from a ViewModel in which is BindingContext of a ContentView.

**Comment by romerotg** [comment] 2024-01-31 14:30
@LuckyDucko, I don't think this should be closed, as the issue is still occurring, as pointed out by @MarcosCostaDev.

@MarcosCostaDev, what do you mean by showing an alert before closing the popup? Can you share a code sample?

**Comment by MarcosCostaDev** [comment] 2024-01-31 23:20
@romerotg showing an alert means executing the alert function from the view model, like the code below.

`Shell.Current.DisplayAlert("An alert Title", "An alert message", "close");`

I execute the alert, then I close the popup via ViewModel using the function `_popupNavigationService.PopAsync()`

**Comment by romerotg** [comment] 2024-02-02 20:28
@LuckyDucko 

I created a PR to fix this issue #107 . Sometimes the `OnLayout` is called even after the page has been popped, and the handler disconnected. I made sure the reference to the handler is nulled out and the page renderer now checks that as well. The previous fix didn't work because the `VirtualView` property throws an exception ("VirtualView cannot be null here") when its inner field is null.

**Comment by tritter** [comment] 2024-02-07 12:57
@LuckyDucko +1 we also encountered this bug, fix looks to work would like to have a new package :)

**Comment by abdullahraiyyan** [comment] 2024-02-15 07:16
I'm experiencing the same issue .is there any workaround?

**Comment by mkazimoto** [comment] 2024-04-05 14:17
I had this same error in CarouselView when calling the Clear() method:
![ERRO](https://github.com/LuckyDucko/Mopups/assets/5958365/a497eaa3-da05-4e02-9116-778dae33a8f4)

The error stopped happening when I changed the DataBinding mode to TwoWay:
![Solution](https://github.com/LuckyDucko/Mopups/assets/5958365/82dab906-248d-4cd0-b3b8-39da4993e753)

**Comment by MarcosCostaDev** [comment] 2024-04-06 16:23
@mkazimoto this looks like not be part of the Mopups.

**Closed** 2024-09-30 02:15 UTC

**Comment by Captnwalker1** [comment] 2026-04-10 18:57
Still seeing this on windows, no errors are actually shown in the app, but seeing crash logs in sentry

<img width="1028" height="232" alt="Image" src="https://github.com/user-attachments/assets/4bdb0a51-7c1c-4223-8f61-9a292348a090" />
